---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
paths:
  /pet/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          examples:
            java:
              value: test
        - name: size
          in: query
          schema:
            type: integer
          example: 37
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponseType'
              examples:
                java:
                  value: new com.example.model.Cat()

components:
  schemas:
    MyResponseType:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Lizard'
      discriminator:
        propertyName: petType
    Cat:
      type: object
      properties:
        name:
          type: string
        petType:
          type: string
    Dog:
      type: object
      properties:
        bark:
          type: string
        petType:
          type: string
    Lizard:
      type: object
      properties:
        lovesRocks:
          type: boolean
        petType:
          type: string
